/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 12
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 19
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_keyword_internal = 1,
  sym_identifier = 2,
  anon_sym_internal = 3,
  anon_sym_external = 4,
  anon_sym_private = 5,
  aux_sym_number_token1 = 6,
  aux_sym_number_token2 = 7,
  sym_float = 8,
  anon_sym_declare = 9,
  anon_sym_SEMI = 10,
  sym_type = 11,
  anon_sym_define = 12,
  anon_sym_LPAREN = 13,
  anon_sym_COMMA = 14,
  anon_sym_RPAREN = 15,
  anon_sym_LBRACE = 16,
  anon_sym_RBRACE = 17,
  anon_sym_var = 18,
  anon_sym_COLON = 19,
  sym_source_file = 20,
  sym__keyword = 21,
  sym_visibility = 22,
  sym_number = 23,
  sym_declare = 24,
  sym_define_var = 25,
  sym_define_fun = 26,
  sym_var_decl = 27,
  sym_instruction = 28,
  sym_label = 29,
  sym_operand = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym_define_fun_repeat1 = 32,
  aux_sym_define_fun_repeat2 = 33,
  aux_sym_define_fun_repeat3 = 34,
  aux_sym_instruction_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_keyword_internal] = "keyword",
  [sym_identifier] = "identifier",
  [anon_sym_internal] = "internal",
  [anon_sym_external] = "external",
  [anon_sym_private] = "private",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [sym_float] = "float",
  [anon_sym_declare] = "declare",
  [anon_sym_SEMI] = ";",
  [sym_type] = "type",
  [anon_sym_define] = "define",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_var] = "var",
  [anon_sym_COLON] = ":",
  [sym_source_file] = "source_file",
  [sym__keyword] = "_keyword",
  [sym_visibility] = "visibility",
  [sym_number] = "number",
  [sym_declare] = "declare",
  [sym_define_var] = "define_var",
  [sym_define_fun] = "define_fun",
  [sym_var_decl] = "var_decl",
  [sym_instruction] = "instruction",
  [sym_label] = "label",
  [sym_operand] = "operand",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_define_fun_repeat1] = "define_fun_repeat1",
  [aux_sym_define_fun_repeat2] = "define_fun_repeat2",
  [aux_sym_define_fun_repeat3] = "define_fun_repeat3",
  [aux_sym_instruction_repeat1] = "instruction_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_keyword_internal] = sym_keyword_internal,
  [sym_identifier] = sym_identifier,
  [anon_sym_internal] = anon_sym_internal,
  [anon_sym_external] = anon_sym_external,
  [anon_sym_private] = anon_sym_private,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [sym_float] = sym_float,
  [anon_sym_declare] = anon_sym_declare,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_type] = sym_type,
  [anon_sym_define] = anon_sym_define,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_source_file] = sym_source_file,
  [sym__keyword] = sym__keyword,
  [sym_visibility] = sym_visibility,
  [sym_number] = sym_number,
  [sym_declare] = sym_declare,
  [sym_define_var] = sym_define_var,
  [sym_define_fun] = sym_define_fun,
  [sym_var_decl] = sym_var_decl,
  [sym_instruction] = sym_instruction,
  [sym_label] = sym_label,
  [sym_operand] = sym_operand,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_define_fun_repeat1] = aux_sym_define_fun_repeat1,
  [aux_sym_define_fun_repeat2] = aux_sym_define_fun_repeat2,
  [aux_sym_define_fun_repeat3] = aux_sym_define_fun_repeat3,
  [aux_sym_instruction_repeat1] = aux_sym_instruction_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_keyword_internal] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_internal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_external] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_private] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_declare] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_define] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__keyword] = {
    .visible = false,
    .named = true,
  },
  [sym_visibility] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_declare] = {
    .visible = true,
    .named = true,
  },
  [sym_define_var] = {
    .visible = true,
    .named = true,
  },
  [sym_define_fun] = {
    .visible = true,
    .named = true,
  },
  [sym_var_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_operand] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_define_fun_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_define_fun_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_define_fun_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_instruction_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
  field_opcode = 3,
  field_param_name = 4,
  field_param_type = 5,
  field_return_type = 6,
  field_type = 7,
  field_vars = 8,
  field_visibility = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
  [field_opcode] = "opcode",
  [field_param_name] = "param_name",
  [field_param_type] = "param_type",
  [field_return_type] = "return_type",
  [field_type] = "type",
  [field_vars] = "vars",
  [field_visibility] = "visibility",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 4},
  [5] = {.index = 10, .length = 1},
  [6] = {.index = 11, .length = 3},
  [7] = {.index = 14, .length = 3},
  [8] = {.index = 17, .length = 2},
  [9] = {.index = 19, .length = 4},
  [10] = {.index = 23, .length = 2},
  [11] = {.index = 25, .length = 4},
  [12] = {.index = 29, .length = 5},
  [13] = {.index = 34, .length = 5},
  [14] = {.index = 39, .length = 6},
  [15] = {.index = 45, .length = 6},
  [16] = {.index = 51, .length = 7},
  [17] = {.index = 58, .length = 7},
  [18] = {.index = 65, .length = 8},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 2},
    {field_visibility, 1},
  [2] =
    {field_name, 2},
    {field_type, 1},
  [4] =
    {field_name, 2},
    {field_return_type, 1},
  [6] =
    {field_param_name, 0, .inherited = true},
    {field_param_name, 1, .inherited = true},
    {field_param_type, 0, .inherited = true},
    {field_param_type, 1, .inherited = true},
  [10] =
    {field_name, 0},
  [11] =
    {field_name, 2},
    {field_return_type, 1},
    {field_vars, 6},
  [14] =
    {field_body, 6},
    {field_name, 2},
    {field_return_type, 1},
  [17] =
    {field_param_name, 2},
    {field_param_type, 1},
  [19] =
    {field_name, 2},
    {field_param_name, 5},
    {field_param_type, 4},
    {field_return_type, 1},
  [23] =
    {field_opcode, 0},
    {field_type, 1},
  [25] =
    {field_body, 7},
    {field_name, 2},
    {field_return_type, 1},
    {field_vars, 6},
  [29] =
    {field_name, 2},
    {field_param_name, 5},
    {field_param_type, 4},
    {field_return_type, 1},
    {field_vars, 8},
  [34] =
    {field_body, 8},
    {field_name, 2},
    {field_param_name, 5},
    {field_param_type, 4},
    {field_return_type, 1},
  [39] =
    {field_name, 2},
    {field_param_name, 5},
    {field_param_name, 6, .inherited = true},
    {field_param_type, 4},
    {field_param_type, 6, .inherited = true},
    {field_return_type, 1},
  [45] =
    {field_body, 9},
    {field_name, 2},
    {field_param_name, 5},
    {field_param_type, 4},
    {field_return_type, 1},
    {field_vars, 8},
  [51] =
    {field_name, 2},
    {field_param_name, 5},
    {field_param_name, 6, .inherited = true},
    {field_param_type, 4},
    {field_param_type, 6, .inherited = true},
    {field_return_type, 1},
    {field_vars, 9},
  [58] =
    {field_body, 9},
    {field_name, 2},
    {field_param_name, 5},
    {field_param_name, 6, .inherited = true},
    {field_param_type, 4},
    {field_param_type, 6, .inherited = true},
    {field_return_type, 1},
  [65] =
    {field_body, 10},
    {field_name, 2},
    {field_param_name, 5},
    {field_param_name, 6, .inherited = true},
    {field_param_type, 4},
    {field_param_type, 6, .inherited = true},
    {field_return_type, 1},
    {field_vars, 9},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '(', 17,
        ')', 19,
        ',', 18,
        '0', 10,
        ':', 22,
        ';', 15,
        '@', 6,
        '{', 20,
        '}', 21,
        '+', 2,
        '-', 2,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == '0') ADVANCE(10);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_keyword_internal);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(13);
      if (lookahead == 'x') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'p') ADVANCE(4);
      if (lookahead == 'v') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'x') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(11);
      if (lookahead == 'f') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'v') ADVANCE(21);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_define);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_declare);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_private);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_external);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_internal);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_keyword_internal] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_internal] = ACTIONS(1),
    [anon_sym_external] = ACTIONS(1),
    [anon_sym_private] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_declare] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_define] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(63),
    [sym_declare] = STATE(8),
    [sym_define_var] = STATE(8),
    [sym_define_fun] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_declare] = ACTIONS(5),
    [anon_sym_define] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(9), 1,
      sym_keyword_internal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 1,
      anon_sym_var,
    STATE(66), 1,
      sym__keyword,
    STATE(3), 2,
      sym_var_decl,
      aux_sym_define_fun_repeat2,
    STATE(9), 3,
      sym_instruction,
      sym_label,
      aux_sym_define_fun_repeat3,
  [25] = 7,
    ACTIONS(9), 1,
      sym_keyword_internal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym__keyword,
    STATE(18), 2,
      sym_var_decl,
      aux_sym_define_fun_repeat2,
    STATE(12), 3,
      sym_instruction,
      sym_label,
      aux_sym_define_fun_repeat3,
  [50] = 7,
    ACTIONS(9), 1,
      sym_keyword_internal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym__keyword,
    STATE(5), 2,
      sym_var_decl,
      aux_sym_define_fun_repeat2,
    STATE(14), 3,
      sym_instruction,
      sym_label,
      aux_sym_define_fun_repeat3,
  [75] = 7,
    ACTIONS(9), 1,
      sym_keyword_internal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym__keyword,
    STATE(18), 2,
      sym_var_decl,
      aux_sym_define_fun_repeat2,
    STATE(15), 3,
      sym_instruction,
      sym_label,
      aux_sym_define_fun_repeat3,
  [100] = 7,
    ACTIONS(9), 1,
      sym_keyword_internal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym__keyword,
    STATE(7), 2,
      sym_var_decl,
      aux_sym_define_fun_repeat2,
    STATE(16), 3,
      sym_instruction,
      sym_label,
      aux_sym_define_fun_repeat3,
  [125] = 7,
    ACTIONS(9), 1,
      sym_keyword_internal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym__keyword,
    STATE(18), 2,
      sym_var_decl,
      aux_sym_define_fun_repeat2,
    STATE(17), 3,
      sym_instruction,
      sym_label,
      aux_sym_define_fun_repeat3,
  [150] = 4,
    ACTIONS(5), 1,
      anon_sym_declare,
    ACTIONS(7), 1,
      anon_sym_define,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(10), 4,
      sym_declare,
      sym_define_var,
      sym_define_fun,
      aux_sym_source_file_repeat1,
  [166] = 5,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym_keyword_internal,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym__keyword,
    STATE(13), 3,
      sym_instruction,
      sym_label,
      aux_sym_define_fun_repeat3,
  [184] = 4,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_declare,
    ACTIONS(38), 1,
      anon_sym_define,
    STATE(10), 4,
      sym_declare,
      sym_define_var,
      sym_define_fun,
      aux_sym_source_file_repeat1,
  [200] = 6,
    ACTIONS(43), 1,
      aux_sym_number_token1,
    ACTIONS(45), 1,
      aux_sym_number_token2,
    ACTIONS(47), 1,
      anon_sym_SEMI,
    STATE(32), 1,
      sym_operand,
    STATE(49), 1,
      sym_number,
    ACTIONS(41), 2,
      sym_identifier,
      sym_float,
  [220] = 5,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym_keyword_internal,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym__keyword,
    STATE(13), 3,
      sym_instruction,
      sym_label,
      aux_sym_define_fun_repeat3,
  [238] = 5,
    ACTIONS(51), 1,
      sym_keyword_internal,
    ACTIONS(54), 1,
      sym_identifier,
    ACTIONS(57), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym__keyword,
    STATE(13), 3,
      sym_instruction,
      sym_label,
      aux_sym_define_fun_repeat3,
  [256] = 5,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym_keyword_internal,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym__keyword,
    STATE(13), 3,
      sym_instruction,
      sym_label,
      aux_sym_define_fun_repeat3,
  [274] = 5,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym_keyword_internal,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym__keyword,
    STATE(13), 3,
      sym_instruction,
      sym_label,
      aux_sym_define_fun_repeat3,
  [292] = 5,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym_keyword_internal,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym__keyword,
    STATE(13), 3,
      sym_instruction,
      sym_label,
      aux_sym_define_fun_repeat3,
  [310] = 5,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(29), 1,
      sym_keyword_internal,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      sym__keyword,
    STATE(13), 3,
      sym_instruction,
      sym_label,
      aux_sym_define_fun_repeat3,
  [328] = 4,
    ACTIONS(67), 1,
      sym_keyword_internal,
    ACTIONS(71), 1,
      anon_sym_var,
    ACTIONS(69), 2,
      sym_identifier,
      anon_sym_RBRACE,
    STATE(18), 2,
      sym_var_decl,
      aux_sym_define_fun_repeat2,
  [343] = 5,
    ACTIONS(43), 1,
      aux_sym_number_token1,
    ACTIONS(45), 1,
      aux_sym_number_token2,
    STATE(49), 1,
      sym_number,
    STATE(51), 1,
      sym_operand,
    ACTIONS(41), 2,
      sym_identifier,
      sym_float,
  [360] = 2,
    STATE(64), 1,
      sym_visibility,
    ACTIONS(74), 3,
      anon_sym_internal,
      anon_sym_external,
      anon_sym_private,
  [369] = 2,
    ACTIONS(76), 2,
      sym_keyword_internal,
      anon_sym_var,
    ACTIONS(78), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [378] = 1,
    ACTIONS(80), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [384] = 1,
    ACTIONS(82), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [390] = 3,
    ACTIONS(84), 1,
      anon_sym_COMMA,
    ACTIONS(86), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      aux_sym_define_fun_repeat1,
  [400] = 3,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      aux_sym_define_fun_repeat1,
  [410] = 1,
    ACTIONS(93), 3,
      sym_identifier,
      sym_keyword_internal,
      anon_sym_RBRACE,
  [416] = 1,
    ACTIONS(95), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [422] = 1,
    ACTIONS(97), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [428] = 1,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [434] = 1,
    ACTIONS(101), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [440] = 1,
    ACTIONS(103), 3,
      sym_identifier,
      sym_keyword_internal,
      anon_sym_RBRACE,
  [446] = 3,
    ACTIONS(105), 1,
      anon_sym_SEMI,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    STATE(40), 1,
      aux_sym_instruction_repeat1,
  [456] = 1,
    ACTIONS(109), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [462] = 1,
    ACTIONS(111), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [468] = 1,
    ACTIONS(113), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [474] = 1,
    ACTIONS(115), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [480] = 3,
    ACTIONS(84), 1,
      anon_sym_COMMA,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    STATE(24), 1,
      aux_sym_define_fun_repeat1,
  [490] = 1,
    ACTIONS(119), 3,
      sym_identifier,
      sym_keyword_internal,
      anon_sym_RBRACE,
  [496] = 1,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [502] = 3,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    ACTIONS(123), 1,
      anon_sym_SEMI,
    STATE(45), 1,
      aux_sym_instruction_repeat1,
  [512] = 1,
    ACTIONS(125), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [518] = 1,
    ACTIONS(127), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [524] = 1,
    ACTIONS(129), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [530] = 1,
    ACTIONS(131), 3,
      sym_identifier,
      sym_keyword_internal,
      anon_sym_RBRACE,
  [536] = 3,
    ACTIONS(133), 1,
      anon_sym_SEMI,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym_instruction_repeat1,
  [546] = 2,
    ACTIONS(138), 1,
      anon_sym_SEMI,
    ACTIONS(140), 1,
      anon_sym_LPAREN,
  [553] = 1,
    ACTIONS(142), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [558] = 2,
    ACTIONS(144), 1,
      sym_type,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
  [565] = 1,
    ACTIONS(148), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [570] = 1,
    ACTIONS(150), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [575] = 1,
    ACTIONS(133), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [580] = 1,
    ACTIONS(152), 1,
      sym_type,
  [584] = 1,
    ACTIONS(154), 1,
      sym_type,
  [588] = 1,
    ACTIONS(156), 1,
      sym_identifier,
  [592] = 1,
    ACTIONS(158), 1,
      anon_sym_LBRACE,
  [596] = 1,
    ACTIONS(160), 1,
      anon_sym_LBRACE,
  [600] = 1,
    ACTIONS(162), 1,
      anon_sym_COLON,
  [604] = 1,
    ACTIONS(164), 1,
      sym_identifier,
  [608] = 1,
    ACTIONS(166), 1,
      anon_sym_SEMI,
  [612] = 1,
    ACTIONS(168), 1,
      sym_identifier,
  [616] = 1,
    ACTIONS(170), 1,
      sym_type,
  [620] = 1,
    ACTIONS(172), 1,
      anon_sym_SEMI,
  [624] = 1,
    ACTIONS(174), 1,
      ts_builtin_sym_end,
  [628] = 1,
    ACTIONS(176), 1,
      sym_identifier,
  [632] = 1,
    ACTIONS(178), 1,
      anon_sym_LBRACE,
  [636] = 1,
    ACTIONS(180), 1,
      sym_type,
  [640] = 1,
    ACTIONS(182), 1,
      sym_identifier,
  [644] = 1,
    ACTIONS(184), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 25,
  [SMALL_STATE(4)] = 50,
  [SMALL_STATE(5)] = 75,
  [SMALL_STATE(6)] = 100,
  [SMALL_STATE(7)] = 125,
  [SMALL_STATE(8)] = 150,
  [SMALL_STATE(9)] = 166,
  [SMALL_STATE(10)] = 184,
  [SMALL_STATE(11)] = 200,
  [SMALL_STATE(12)] = 220,
  [SMALL_STATE(13)] = 238,
  [SMALL_STATE(14)] = 256,
  [SMALL_STATE(15)] = 274,
  [SMALL_STATE(16)] = 292,
  [SMALL_STATE(17)] = 310,
  [SMALL_STATE(18)] = 328,
  [SMALL_STATE(19)] = 343,
  [SMALL_STATE(20)] = 360,
  [SMALL_STATE(21)] = 369,
  [SMALL_STATE(22)] = 378,
  [SMALL_STATE(23)] = 384,
  [SMALL_STATE(24)] = 390,
  [SMALL_STATE(25)] = 400,
  [SMALL_STATE(26)] = 410,
  [SMALL_STATE(27)] = 416,
  [SMALL_STATE(28)] = 422,
  [SMALL_STATE(29)] = 428,
  [SMALL_STATE(30)] = 434,
  [SMALL_STATE(31)] = 440,
  [SMALL_STATE(32)] = 446,
  [SMALL_STATE(33)] = 456,
  [SMALL_STATE(34)] = 462,
  [SMALL_STATE(35)] = 468,
  [SMALL_STATE(36)] = 474,
  [SMALL_STATE(37)] = 480,
  [SMALL_STATE(38)] = 490,
  [SMALL_STATE(39)] = 496,
  [SMALL_STATE(40)] = 502,
  [SMALL_STATE(41)] = 512,
  [SMALL_STATE(42)] = 518,
  [SMALL_STATE(43)] = 524,
  [SMALL_STATE(44)] = 530,
  [SMALL_STATE(45)] = 536,
  [SMALL_STATE(46)] = 546,
  [SMALL_STATE(47)] = 553,
  [SMALL_STATE(48)] = 558,
  [SMALL_STATE(49)] = 565,
  [SMALL_STATE(50)] = 570,
  [SMALL_STATE(51)] = 575,
  [SMALL_STATE(52)] = 580,
  [SMALL_STATE(53)] = 584,
  [SMALL_STATE(54)] = 588,
  [SMALL_STATE(55)] = 592,
  [SMALL_STATE(56)] = 596,
  [SMALL_STATE(57)] = 600,
  [SMALL_STATE(58)] = 604,
  [SMALL_STATE(59)] = 608,
  [SMALL_STATE(60)] = 612,
  [SMALL_STATE(61)] = 616,
  [SMALL_STATE(62)] = 620,
  [SMALL_STATE(63)] = 624,
  [SMALL_STATE(64)] = 628,
  [SMALL_STATE(65)] = 632,
  [SMALL_STATE(66)] = 636,
  [SMALL_STATE(67)] = 640,
  [SMALL_STATE(68)] = 644,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_define_fun_repeat3, 2, 0, 0), SHIFT_REPEAT(66),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_define_fun_repeat3, 2, 0, 0), SHIFT_REPEAT(57),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_define_fun_repeat3, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_define_fun_repeat2, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_define_fun_repeat2, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_define_fun_repeat2, 2, 0, 0), SHIFT_REPEAT(53),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_decl, 4, 0, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_decl, 4, 0, 2),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_var, 4, 0, 2),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 12, 0, 18),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_define_fun_repeat1, 2, 0, 4), SHIFT_REPEAT(52),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_define_fun_repeat1, 2, 0, 4),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, 0, 5),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 8, 0, 6),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 8, 0, 7),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 9, 0, 9),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declare, 4, 0, 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 3, 0, 10),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 9, 0, 11),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 10, 0, 12),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 10, 0, 13),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 10, 0, 14),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 4, 0, 10),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 7, 0, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 11, 0, 15),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 11, 0, 16),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 11, 0, 17),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 5, 0, 10),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_define_fun_repeat1, 3, 0, 8),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operand, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [174] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_visibility, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hir(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_keyword_internal,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hir",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
