/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 18
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_keyword_internal = 1,
  sym_identifier = 2,
  anon_sym_internal = 3,
  anon_sym_external = 4,
  anon_sym_private = 5,
  aux_sym_number_token1 = 6,
  aux_sym_number_token2 = 7,
  sym_float = 8,
  anon_sym_declare = 9,
  anon_sym_SEMI = 10,
  sym_type = 11,
  anon_sym_define = 12,
  anon_sym_LPAREN = 13,
  anon_sym_COMMA = 14,
  anon_sym_RPAREN = 15,
  anon_sym_LBRACE = 16,
  anon_sym_RBRACE = 17,
  anon_sym_var = 18,
  anon_sym_COLON = 19,
  sym_source_file = 20,
  sym__keyword = 21,
  sym_visibility = 22,
  sym_number = 23,
  sym_declare = 24,
  sym_define_var = 25,
  sym_define_fun = 26,
  sym_var_decl = 27,
  sym_instruction = 28,
  sym_label = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym_define_fun_repeat1 = 31,
  aux_sym_define_fun_repeat2 = 32,
  aux_sym_instruction_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_keyword_internal] = "keyword",
  [sym_identifier] = "identifier",
  [anon_sym_internal] = "internal",
  [anon_sym_external] = "external",
  [anon_sym_private] = "private",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [sym_float] = "float",
  [anon_sym_declare] = "declare",
  [anon_sym_SEMI] = ";",
  [sym_type] = "type",
  [anon_sym_define] = "define",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_var] = "var",
  [anon_sym_COLON] = ":",
  [sym_source_file] = "source_file",
  [sym__keyword] = "_keyword",
  [sym_visibility] = "visibility",
  [sym_number] = "number",
  [sym_declare] = "declare",
  [sym_define_var] = "define_var",
  [sym_define_fun] = "define_fun",
  [sym_var_decl] = "var_decl",
  [sym_instruction] = "instruction",
  [sym_label] = "label",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_define_fun_repeat1] = "define_fun_repeat1",
  [aux_sym_define_fun_repeat2] = "define_fun_repeat2",
  [aux_sym_instruction_repeat1] = "instruction_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_keyword_internal] = sym_keyword_internal,
  [sym_identifier] = sym_identifier,
  [anon_sym_internal] = anon_sym_internal,
  [anon_sym_external] = anon_sym_external,
  [anon_sym_private] = anon_sym_private,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [sym_float] = sym_float,
  [anon_sym_declare] = anon_sym_declare,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_type] = sym_type,
  [anon_sym_define] = anon_sym_define,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_source_file] = sym_source_file,
  [sym__keyword] = sym__keyword,
  [sym_visibility] = sym_visibility,
  [sym_number] = sym_number,
  [sym_declare] = sym_declare,
  [sym_define_var] = sym_define_var,
  [sym_define_fun] = sym_define_fun,
  [sym_var_decl] = sym_var_decl,
  [sym_instruction] = sym_instruction,
  [sym_label] = sym_label,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_define_fun_repeat1] = aux_sym_define_fun_repeat1,
  [aux_sym_define_fun_repeat2] = aux_sym_define_fun_repeat2,
  [aux_sym_instruction_repeat1] = aux_sym_instruction_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_keyword_internal] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_internal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_external] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_private] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_declare] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_define] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__keyword] = {
    .visible = false,
    .named = true,
  },
  [sym_visibility] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_declare] = {
    .visible = true,
    .named = true,
  },
  [sym_define_var] = {
    .visible = true,
    .named = true,
  },
  [sym_define_fun] = {
    .visible = true,
    .named = true,
  },
  [sym_var_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_define_fun_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_define_fun_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_instruction_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
  field_opcode = 3,
  field_operands = 4,
  field_param_name = 5,
  field_param_type = 6,
  field_return_type = 7,
  field_type = 8,
  field_vars = 9,
  field_visibility = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
  [field_opcode] = "opcode",
  [field_operands] = "operands",
  [field_param_name] = "param_name",
  [field_param_type] = "param_type",
  [field_return_type] = "return_type",
  [field_type] = "type",
  [field_vars] = "vars",
  [field_visibility] = "visibility",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 1},
  [5] = {.index = 7, .length = 1},
  [6] = {.index = 8, .length = 4},
  [7] = {.index = 12, .length = 1},
  [8] = {.index = 13, .length = 4},
  [9] = {.index = 17, .length = 4},
  [10] = {.index = 21, .length = 2},
  [11] = {.index = 23, .length = 4},
  [12] = {.index = 27, .length = 2},
  [13] = {.index = 29, .length = 6},
  [14] = {.index = 35, .length = 6},
  [15] = {.index = 41, .length = 3},
  [16] = {.index = 44, .length = 8},
  [17] = {.index = 52, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 2},
    {field_visibility, 1},
  [2] =
    {field_name, 2},
    {field_type, 1},
  [4] =
    {field_name, 2},
    {field_return_type, 1},
  [6] =
    {field_vars, 0},
  [7] =
    {field_body, 0},
  [8] =
    {field_param_name, 0, .inherited = true},
    {field_param_name, 1, .inherited = true},
    {field_param_type, 0, .inherited = true},
    {field_param_type, 1, .inherited = true},
  [12] =
    {field_name, 0},
  [13] =
    {field_body, 6, .inherited = true},
    {field_name, 2},
    {field_return_type, 1},
    {field_vars, 6, .inherited = true},
  [17] =
    {field_body, 0, .inherited = true},
    {field_body, 1, .inherited = true},
    {field_vars, 0, .inherited = true},
    {field_vars, 1, .inherited = true},
  [21] =
    {field_param_name, 2},
    {field_param_type, 1},
  [23] =
    {field_name, 2},
    {field_param_name, 5},
    {field_param_type, 4},
    {field_return_type, 1},
  [27] =
    {field_opcode, 0},
    {field_type, 1},
  [29] =
    {field_body, 8, .inherited = true},
    {field_name, 2},
    {field_param_name, 5},
    {field_param_type, 4},
    {field_return_type, 1},
    {field_vars, 8, .inherited = true},
  [35] =
    {field_name, 2},
    {field_param_name, 5},
    {field_param_name, 6, .inherited = true},
    {field_param_type, 4},
    {field_param_type, 6, .inherited = true},
    {field_return_type, 1},
  [41] =
    {field_opcode, 0},
    {field_operands, 2},
    {field_type, 1},
  [44] =
    {field_body, 9, .inherited = true},
    {field_name, 2},
    {field_param_name, 5},
    {field_param_name, 6, .inherited = true},
    {field_param_type, 4},
    {field_param_type, 6, .inherited = true},
    {field_return_type, 1},
    {field_vars, 9, .inherited = true},
  [52] =
    {field_opcode, 0},
    {field_operands, 2},
    {field_operands, 3},
    {field_type, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '(', 17,
        ')', 19,
        ',', 18,
        '0', 10,
        ':', 22,
        ';', 15,
        '@', 6,
        '{', 20,
        '}', 21,
        '+', 2,
        '-', 2,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == '0') ADVANCE(10);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_keyword_internal);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(13);
      if (lookahead == 'x') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'p') ADVANCE(4);
      if (lookahead == 'v') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'x') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(11);
      if (lookahead == 'f') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'v') ADVANCE(21);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_define);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 30:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_declare);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_private);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_external);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_internal);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_keyword_internal] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_internal] = ACTIONS(1),
    [anon_sym_external] = ACTIONS(1),
    [anon_sym_private] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_declare] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_define] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(49),
    [sym_declare] = STATE(10),
    [sym_define_var] = STATE(10),
    [sym_define_fun] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_declare] = ACTIONS(5),
    [anon_sym_define] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(9), 1,
      sym_keyword_internal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 1,
      anon_sym_var,
    STATE(7), 1,
      aux_sym_define_fun_repeat2,
    STATE(14), 1,
      sym_var_decl,
    STATE(54), 1,
      sym__keyword,
    STATE(13), 2,
      sym_instruction,
      sym_label,
  [26] = 8,
    ACTIONS(9), 1,
      sym_keyword_internal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_define_fun_repeat2,
    STATE(14), 1,
      sym_var_decl,
    STATE(54), 1,
      sym__keyword,
    STATE(13), 2,
      sym_instruction,
      sym_label,
  [52] = 8,
    ACTIONS(9), 1,
      sym_keyword_internal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      aux_sym_define_fun_repeat2,
    STATE(14), 1,
      sym_var_decl,
    STATE(54), 1,
      sym__keyword,
    STATE(13), 2,
      sym_instruction,
      sym_label,
  [78] = 8,
    ACTIONS(9), 1,
      sym_keyword_internal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_define_fun_repeat2,
    STATE(14), 1,
      sym_var_decl,
    STATE(54), 1,
      sym__keyword,
    STATE(13), 2,
      sym_instruction,
      sym_label,
  [104] = 8,
    ACTIONS(9), 1,
      sym_keyword_internal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      aux_sym_define_fun_repeat2,
    STATE(14), 1,
      sym_var_decl,
    STATE(54), 1,
      sym__keyword,
    STATE(13), 2,
      sym_instruction,
      sym_label,
  [130] = 8,
    ACTIONS(25), 1,
      sym_keyword_internal,
    ACTIONS(28), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    ACTIONS(33), 1,
      anon_sym_var,
    STATE(7), 1,
      aux_sym_define_fun_repeat2,
    STATE(14), 1,
      sym_var_decl,
    STATE(54), 1,
      sym__keyword,
    STATE(13), 2,
      sym_instruction,
      sym_label,
  [156] = 8,
    ACTIONS(9), 1,
      sym_keyword_internal,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      aux_sym_define_fun_repeat2,
    STATE(14), 1,
      sym_var_decl,
    STATE(54), 1,
      sym__keyword,
    STATE(13), 2,
      sym_instruction,
      sym_label,
  [182] = 4,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      anon_sym_declare,
    ACTIONS(43), 1,
      anon_sym_define,
    STATE(9), 4,
      sym_declare,
      sym_define_var,
      sym_define_fun,
      aux_sym_source_file_repeat1,
  [198] = 4,
    ACTIONS(5), 1,
      anon_sym_declare,
    ACTIONS(7), 1,
      anon_sym_define,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    STATE(9), 4,
      sym_declare,
      sym_define_var,
      sym_define_fun,
      aux_sym_source_file_repeat1,
  [214] = 5,
    ACTIONS(50), 1,
      aux_sym_number_token1,
    ACTIONS(52), 1,
      aux_sym_number_token2,
    ACTIONS(54), 1,
      anon_sym_SEMI,
    STATE(33), 1,
      sym_number,
    ACTIONS(48), 2,
      sym_identifier,
      sym_float,
  [231] = 4,
    ACTIONS(50), 1,
      aux_sym_number_token1,
    ACTIONS(52), 1,
      aux_sym_number_token2,
    STATE(39), 1,
      sym_number,
    ACTIONS(56), 2,
      sym_identifier,
      sym_float,
  [245] = 2,
    ACTIONS(58), 2,
      sym_keyword_internal,
      anon_sym_var,
    ACTIONS(60), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [254] = 2,
    ACTIONS(62), 2,
      sym_keyword_internal,
      anon_sym_var,
    ACTIONS(64), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [263] = 2,
    ACTIONS(66), 2,
      sym_keyword_internal,
      anon_sym_var,
    ACTIONS(68), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [272] = 2,
    STATE(51), 1,
      sym_visibility,
    ACTIONS(70), 3,
      anon_sym_internal,
      anon_sym_external,
      anon_sym_private,
  [281] = 2,
    ACTIONS(72), 2,
      sym_keyword_internal,
      anon_sym_var,
    ACTIONS(74), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [290] = 2,
    ACTIONS(76), 2,
      sym_keyword_internal,
      anon_sym_var,
    ACTIONS(78), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [299] = 2,
    ACTIONS(80), 2,
      sym_keyword_internal,
      anon_sym_var,
    ACTIONS(82), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [308] = 2,
    ACTIONS(84), 2,
      sym_keyword_internal,
      anon_sym_var,
    ACTIONS(86), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [317] = 3,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    ACTIONS(90), 1,
      anon_sym_RPAREN,
    STATE(24), 1,
      aux_sym_define_fun_repeat1,
  [327] = 3,
    ACTIONS(92), 1,
      anon_sym_SEMI,
    ACTIONS(94), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      aux_sym_instruction_repeat1,
  [337] = 3,
    ACTIONS(88), 1,
      anon_sym_COMMA,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    STATE(21), 1,
      aux_sym_define_fun_repeat1,
  [347] = 3,
    ACTIONS(99), 1,
      anon_sym_COMMA,
    ACTIONS(102), 1,
      anon_sym_RPAREN,
    STATE(24), 1,
      aux_sym_define_fun_repeat1,
  [357] = 1,
    ACTIONS(104), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [363] = 1,
    ACTIONS(106), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [369] = 1,
    ACTIONS(108), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [375] = 1,
    ACTIONS(110), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [381] = 1,
    ACTIONS(112), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [387] = 1,
    ACTIONS(114), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [393] = 1,
    ACTIONS(116), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [399] = 1,
    ACTIONS(118), 3,
      ts_builtin_sym_end,
      anon_sym_declare,
      anon_sym_define,
  [405] = 3,
    ACTIONS(120), 1,
      anon_sym_SEMI,
    ACTIONS(122), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      aux_sym_instruction_repeat1,
  [415] = 3,
    ACTIONS(122), 1,
      anon_sym_COMMA,
    ACTIONS(124), 1,
      anon_sym_SEMI,
    STATE(22), 1,
      aux_sym_instruction_repeat1,
  [425] = 1,
    ACTIONS(126), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [430] = 2,
    ACTIONS(128), 1,
      anon_sym_SEMI,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
  [437] = 1,
    ACTIONS(132), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [442] = 2,
    ACTIONS(134), 1,
      sym_type,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
  [449] = 1,
    ACTIONS(92), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [454] = 1,
    ACTIONS(138), 1,
      sym_identifier,
  [458] = 1,
    ACTIONS(140), 1,
      sym_identifier,
  [462] = 1,
    ACTIONS(142), 1,
      anon_sym_SEMI,
  [466] = 1,
    ACTIONS(144), 1,
      anon_sym_LBRACE,
  [470] = 1,
    ACTIONS(146), 1,
      sym_identifier,
  [474] = 1,
    ACTIONS(148), 1,
      sym_identifier,
  [478] = 1,
    ACTIONS(150), 1,
      anon_sym_LBRACE,
  [482] = 1,
    ACTIONS(152), 1,
      anon_sym_LBRACE,
  [486] = 1,
    ACTIONS(154), 1,
      anon_sym_COLON,
  [490] = 1,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
  [494] = 1,
    ACTIONS(158), 1,
      sym_identifier,
  [498] = 1,
    ACTIONS(160), 1,
      sym_identifier,
  [502] = 1,
    ACTIONS(162), 1,
      anon_sym_SEMI,
  [506] = 1,
    ACTIONS(164), 1,
      sym_type,
  [510] = 1,
    ACTIONS(166), 1,
      sym_type,
  [514] = 1,
    ACTIONS(168), 1,
      sym_type,
  [518] = 1,
    ACTIONS(170), 1,
      sym_type,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 78,
  [SMALL_STATE(6)] = 104,
  [SMALL_STATE(7)] = 130,
  [SMALL_STATE(8)] = 156,
  [SMALL_STATE(9)] = 182,
  [SMALL_STATE(10)] = 198,
  [SMALL_STATE(11)] = 214,
  [SMALL_STATE(12)] = 231,
  [SMALL_STATE(13)] = 245,
  [SMALL_STATE(14)] = 254,
  [SMALL_STATE(15)] = 263,
  [SMALL_STATE(16)] = 272,
  [SMALL_STATE(17)] = 281,
  [SMALL_STATE(18)] = 290,
  [SMALL_STATE(19)] = 299,
  [SMALL_STATE(20)] = 308,
  [SMALL_STATE(21)] = 317,
  [SMALL_STATE(22)] = 327,
  [SMALL_STATE(23)] = 337,
  [SMALL_STATE(24)] = 347,
  [SMALL_STATE(25)] = 357,
  [SMALL_STATE(26)] = 363,
  [SMALL_STATE(27)] = 369,
  [SMALL_STATE(28)] = 375,
  [SMALL_STATE(29)] = 381,
  [SMALL_STATE(30)] = 387,
  [SMALL_STATE(31)] = 393,
  [SMALL_STATE(32)] = 399,
  [SMALL_STATE(33)] = 405,
  [SMALL_STATE(34)] = 415,
  [SMALL_STATE(35)] = 425,
  [SMALL_STATE(36)] = 430,
  [SMALL_STATE(37)] = 437,
  [SMALL_STATE(38)] = 442,
  [SMALL_STATE(39)] = 449,
  [SMALL_STATE(40)] = 454,
  [SMALL_STATE(41)] = 458,
  [SMALL_STATE(42)] = 462,
  [SMALL_STATE(43)] = 466,
  [SMALL_STATE(44)] = 470,
  [SMALL_STATE(45)] = 474,
  [SMALL_STATE(46)] = 478,
  [SMALL_STATE(47)] = 482,
  [SMALL_STATE(48)] = 486,
  [SMALL_STATE(49)] = 490,
  [SMALL_STATE(50)] = 494,
  [SMALL_STATE(51)] = 498,
  [SMALL_STATE(52)] = 502,
  [SMALL_STATE(53)] = 506,
  [SMALL_STATE(54)] = 510,
  [SMALL_STATE(55)] = 514,
  [SMALL_STATE(56)] = 518,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_define_fun_repeat2, 2, 0, 9), SHIFT_REPEAT(54),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_define_fun_repeat2, 2, 0, 9), SHIFT_REPEAT(48),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_define_fun_repeat2, 2, 0, 9),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_define_fun_repeat2, 2, 0, 9), SHIFT_REPEAT(53),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_define_fun_repeat2, 1, 0, 5),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_define_fun_repeat2, 1, 0, 5),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_define_fun_repeat2, 1, 0, 4),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_define_fun_repeat2, 1, 0, 4),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label, 2, 0, 7),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, 0, 7),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 5, 0, 17),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 5, 0, 17),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_decl, 4, 0, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_decl, 4, 0, 2),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 3, 0, 12),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 3, 0, 12),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 4, 0, 15),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 4, 0, 15),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_define_fun_repeat1, 2, 0, 6), SHIFT_REPEAT(55),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_define_fun_repeat1, 2, 0, 6),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 7, 0, 3),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 8, 0, 8),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 9, 0, 11),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declare, 4, 0, 1),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 10, 0, 14),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_var, 4, 0, 2),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 11, 0, 16),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_fun, 10, 0, 13),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_define_fun_repeat1, 3, 0, 10),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [156] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_visibility, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hir(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_keyword_internal,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hir",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
